### ISSUE TITLE
[python] MRU/MFU prioritisation not working

### ISSUE THREAD

**Issue by AdamPS** [albertlauncher/plugins#100]
#### Description
Since the major interface change, prioritisation of completions based on history / recently used doesn't seem to be working for python plug-ins. This is true for both built-ins and my own ones.

#### Expected behavior
A completion that has been used several times should move to the top of the list.

#### Steps to reproduce
1. Open the launcher and type the trigger for a python plug-in
2. Type a few characters then choose a completion that is not the first in the list
3. Repeat several times

#### Source
PPA version 0.20.13

#### Debug output

<details>
17:15:42 [debg:albert] TIME:      2 µs ['globalsearch':'']
17:15:44 [debg:albert] TIME: 1615444 µs ['locate':'man']
17:15:47 [debg:albert] Opening URL 'file:///boot/grub/x86_64-efi/command.lst'
17:15:47 [debg:albert] UsageHistory::addActivation  10451 µs
17:15:47 [debg:albert] Query deleted. [#1 '']
17:15:47 [debg:albert] Query deleted. [#0 '']
17:15:47 [debg:albert] UsageHistory::mruScores   3247 µs
17:15:50 [debg:albert] TIME: 1737593 µs ['locate':'man']
17:15:51 [debg:albert] Opening URL 'file:///boot/grub/x86_64-efi/command.lst'
17:15:51 [debg:albert] UsageHistory::addActivation   8821 µs
17:15:51 [debg:albert] Query deleted. [#2 'man']
17:15:51 [debg:albert] UsageHistory::mruScores   3195 µs
17:15:54 [debg:albert] TIME: 1670592 µs ['locate':'man']
17:15:55 [debg:albert] Opening URL 'file:///boot/grub/x86_64-efi/command.lst'
17:15:55 [debg:albert] UsageHistory::addActivation  10443 µs
17:15:55 [debg:albert] Query deleted. [#3 'man']
17:15:56 [debg:albert] UsageHistory::mruScores   2824 µs
</details>

**Comment by ManuelSchneid3r** [comment]
Python handlers atm can only be of type QueryHandler. This one is the basic query handler which is run exclusively. I must not complete before items are shown, they pop up in the list as the handler adds them. As such items cannot be rearranged. 

GlobalQueryHandlers on the other side return ordered (scored) items and have to finish handling of the query before mru scores are applied and the items are sorted. Unfortunately I had troubles getting the GlobalQueryHandler exposed in the python API. Thats why I had to end the winter of code. I will continue there as soon I have time.

You can check the state [here](https://github.com/albertlauncher/plugins/blob/master/python/src/plugin.cpp#L67-L78). I forgot the exact dealbreaker. Maybe you have some ideas.

**Comment by AdamPS** [comment]
Thanks for the explanation.

Would GlobalQueryHandler/IndexQueryHandler also allow triggerless python plug-ins?? These two together would be a big improvement - otherwise I have to rewrite my plug-in in C😃. I might take a look later (bit busy right now!) as sometimes a second person can see something the first developer didn't spot.

**Comment by ManuelSchneid3r** [comment]
> Would GlobalQueryHandler/IndexQueryHandler also allow triggerless python plug-ins?? 
yes

> These two together would be a big improvement - otherwise I have to rewrite my plug-in in C😃. I might take a look later (bit busy right now!) as sometimes a second person can see something the first developer didn't spot.
sure, but beware the glue code is really time consuming. pybind is not perfect and I always try to reduce the boilerplate imposed on plugin devs

**Comment by ManuelSchneid3r** [comment]
check the v0.21 branch. 

> These two together would be a big improvement

well anyway python will never support multithreading and globalqueryhandlers are not optimal since they may make a query end up being processed serially. Id rather not use globalqueryhandlers if it is possible. indexqueryhandlers just provide items, the matching and indexing is done in the core/c++ are and as such are parallelized.

> I might take a look later (bit busy right now!) as sometimes a second person can see something the first developer didn't spot.

v0.21 now allows globalqueryhandlers. the indexqueryhandler still needs some work. but I refuse to give guarantees. been there already. I dont want to dissapoint you :D

**Comment by AdamPS** [comment]
Amazing, many thanks. Do you have any way to download a development image pre-built?

**Comment by ManuelSchneid3r** [comment]
Well atm the change is relavant to devs only. If you are one you should know how to git pull, cmake, and make.

**Comment by ManuelSchneid3r** [comment]
I have to test this change for a while now. I will add the indexqueryhandler and fallbackprovider too soon.

**Comment by AdamPS** [comment]
> If you are one you should know how to git pull, cmake, and make.
Sure, I know how - just trying to save time😃

**Comment by ManuelSchneid3r** [comment]
Sure I understand. maintaining a dev image does not come for free as well though 😄

**Comment by ManuelSchneid3r** [comment]
It's not that common that I have to branch because the changes are probably errorprone. Most of the time I can just push things because the work out almost every time. On the other side I had this differentiation long time ago but I was probably the only one using it.

**Comment by AdamPS** [comment]
> maintaining a dev image does not come for free as well though

Of course - I only asked in case you were already doing it, in which case I should make use of it😃
