### ISSUE TITLE
albert 0.20.13 in ubuntu 22.04 cannot activate fcitx(fcitx5) IME

### ISSUE THREAD

**Issue by x3y1** [albertlauncher/plugins#101]
#### Description
I have installed albert 0.20.13 in ubuntu 22.04, but when albert is activated, I cannot input any Chinese character, even the IME cannot be activated.

#### Expected behavior
When albert is activated, I can input Chinese characters normally.

#### Steps to reproduce
echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list
curl -fsSL https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_manuelschneid3r.gpg > /dev/null
sudo apt update
sudo apt install albert

sudo apt install fcitx5

restart the computer, launch albert, then press ctrl+space, fcitx5 cannot be activated.

**Comment by ManuelSchneid3r** [comment]
i tried to test this one and could not run fcitx at all. in my eyes this suggests that the problem could lie in a complicated and error prone setup. have you tried to open it in any other qt6 app?

**Comment by Lcify** [comment]
I also encountered this problem

**Comment by ManuelSchneid3r** [comment]
> I also encountered this problem

Well you could help out debugging. Do you have another qt6 app which works well with the IM?

**Comment by Lcify** [comment]
i'm sorry, i don't install other software that is using QT6. i install fcitx5 and sougoupinyin that input Chinese.
When i open Input box of albert, i can't cutover mode that input Chinese (sougoupinyin).
![image](https://user-images.githubusercontent.com/60638114/235668618-a5b41bdf-4096-4e92-b63b-e633fdebe007.png)

**Comment by Lcify** [comment]
> > I also encountered this problem
> 
> Well you could help out debugging. Do you have another qt6 app which works well with the IM?

I'm sorry, I didn't install any other software that uses QT6. I installed Fcitx5 and Sogou Pinyin for inputting Chinese. When I open the input box of Albert, I am unable to switch the input mode to Chinese (Sogou Pinyin).
![image](https://user-images.githubusercontent.com/60638114/235670341-7d94d3fe-f83d-4e8c-8c57-290c35cfad0d.png)

**Comment by ManuelSchneid3r** [comment]
Considering the eyes 👀 you have to understand that I am not a desktop system or toolkit developer. I use a  pretty much standard input line. I did not change anything specifically. If there are problems it's likely that qt or your vendor messed up. That's why I asked if other qt apps make problems as well. If so then this issue can be closed.

Have you tried other qt apps like e.g. Virtualbox, telegram, vlc?

**Comment by ManuelSchneid3r** [comment]
Unfortunately I pretty often have to encounter this situation, where people think standalone devs can be delegated to fix problems in other, maybe related projects because the devs of these projects don't respond or refuse to fix things (*ehem* dmw and other “wow <1000LOC" projects)

**Comment by Lcify** [comment]
> Considering the eyes eyes you have to understand that I am not a desktop system or toolkit developer. I use a pretty much standard input line. I did not change anything specifically. If there are problems it's likely that qt or your vendor messed up. That's why I asked if other qt apps make problems as well. If so then this issue can be closed.
> 
> Have you tried other qt apps like e.g. Virtualbox, telegram, vlc?

Thank you for taking the time to pay attention to this problem, I am also a developer, I can understand, but currently I have no better way to solve this problem.
I try to input Chinese in vlc, it can work
![image](https://user-images.githubusercontent.com/60638114/235823166-4c9a1852-dbef-49a3-97ae-eeeb8c5ce183.png)

**Comment by ManuelSchneid3r** [comment]
Does it work in telegram desktop?

**Comment by ManuelSchneid3r** [comment]
https://archlinux.org/packages/community/x86_64/telegram-desktop/
