### ISSUE TITLE
Applications lists entries that have already been deleted

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [albertlauncher/plugins#102]
#### Description
I deleted an entry in the menu I had manually created. It is now gone from the start menu search, but still shows up in Albert.

#### Expected behavior
I would expect Albert to forget about deleted entries.

#### Steps to reproduce
Create a new menu entry via the menu editor.
Check that Albert detects it.
Delete the entry via the menu editor.
See that Albert still has it.

#### Source
Opensuse repository

#### Debug output
Unknown option 'd'.lb

#### System Info
OS: Linux Mint 20.2 Cinnamon 64-bit
Albert Version: 0.17.2

**Comment by ManuelSchneid3r** [comment]
@Adrian-Bielefeldt i.e. does the menu follow the xdg desktop entry spec?
