### ISSUE TITLE
[emoji picker] NameError: name "TriggerQueryHandler" is not defined

### ISSUE THREAD

**Issue by dreamcat4** [albertlauncher/plugins#104]
#### Description

Hi,
Just this plugin did not enable... unfortunately the google of it's python error message - there is nothing returned at google to answer. This is on the latest version of ubuntu. With the latest released version of albert. So maybe something relevant just needs to be updated in it's deps?

#### Steps to reproduce

* Update to latest official release of albert
* Enable Albert python plugins from albert settings, in the plugins tab.
* Enable plugin --> see error msg in the plugin's setting's page for emoji picker

#### Source

In latest albert version (after upgrade).

Albert version: `Albert Launcher 0.21.0`
OS / Distro: `Ubuntu 23.04`
Python system version: `3.11.2`

#### Debug output

![ksnip_20230519-103121](https://github.com/albertlauncher/plugins/assets/63074/448dfc5a-c46c-46b7-9e59-6d2c7ae960e0)

Output of `albert -d` when run in a terminal
```sh
θ79° [id:~] $ albert -d
        Albert version: 0.21.0
            Build date: May 18 2023 15:51:36
            Qt version: 6.4.2
             Build ABI: x86_64-little_endian-lp64
  Arch (build/current): x86_64/x86_64
 Kernel (type/version): linux/6.2.12-x64v1-xanmod1
                    OS: Ubuntu 23.04
     OS (type/version): ubuntu/23.04
 $QT_QPA_PLATFORMTHEME: qt5ct
         Platform name: xcb
                  Font: Noto Sans,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1
       Binary location: /usr/bin/albert
                  $PWD: /home/id
                $SHELL: /bin/bash
                 $LANG: en_GB.UTF-8
              Language: English
                Locale: en_GB
     $XDG_SESSION_TYPE: x11
  $XDG_CURRENT_DESKTOP: KDE
      $DESKTOP_SESSION: plasma
  $XDG_SESSION_DESKTOP: KDE
            Icon theme: BeautyLine
10:42:37 [crit:albert] Application has not been terminated graciously
```

**Comment by ManuelSchneid3r** [comment]
See https://github.com/albertlauncher/albert/issues/1238
