### ISSUE TITLE
Index query handler

### ISSUE THREAD

**Issue by AdamPS** [albertlauncher/plugins#108]
#### Description
The python support in the new version is great, many thanks. Please can you help me with two problems/questions?

#### Expected behavior
1) I would like to match completions by typing the middle of the item name, not only the beginning please. For example if the name is "big bad wolf", it works to match "big". It doesn't work to match for "bad" or "wolf" or "ad wo".
2) I would like a way to rebuild the index please.

Both of these work with the built-in "Files" plug-in.

#### Steps to reproduce
See above

#### Source
[ppa](http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu) v0.21.1

#### Debug output

There's not really anything relevant in the debug output.

**Comment by AdamPS** [comment]
Sorry I was wrong for the first part, I believe I see how it works now. It matches after any "separator" and I can configure the separators in the search settings.

I'm still stuck on the second part, how to rebuild the index. Many thanks.

**Comment by ManuelSchneid3r** [comment]
> I'm still stuck on the second part, how to rebuild the index. Many thanks.

Just call the method [you implemented](https://github.com/albertlauncher/python/blob/master/albert.pyi#L312)

**Comment by AdamPS** [comment]
Great thanks for the advice. So I guess I could create an item/action that would rebuild the index, and I could do this in each Index query handler. I could even create a base class to wrap IndexQueryHandler including this code.

Even a single command could loop through all indexed handlers (python or C) and re-index them all, however that's more complex to write, probably it would have to be done in C.
