### ISSUE TITLE
[wbm] Problem of flashing when trigger the window

### ISSUE THREAD

**Issue by TexDash** [albertlauncher/plugins#110]
#### Description
When I trigger Albert with some previous input, it flashes, which is annoying:

![Peek 2023-07-07 18-30](https://github.com/albertlauncher/albert/assets/138767936/ed208cfd-a61f-4605-b4f7-eef167b579bd)

#### Expected behavior
I expect it to show the input box only first and then some content listed (after potentially some processing). But now the behavior is, showing some previous content, input box only, and finally, the updated content, which is the cause of the flashing.

#### Steps to reproduce
As in the screenshot.

#### Source
prebuilt version 0.21.1 on Debian 12

**Comment by ManuelSchneid3r** [comment]
@TexDash ?

**Comment by ManuelSchneid3r** [comment]
Seems abandoned.

**Comment by ManuelSchneid3r** [comment]
That's cool! Why don't you send a PR?
