### ISSUE TITLE
[files] application does not open

### ISSUE THREAD

**Issue by b10n** [albertlauncher/plugins#111]
#### Description
Opening a file does not work, unless opened via the alternative actions menu.

#### Expected behavior
The default application for the file type opens the file.

#### Steps to reproduce
1. Open Albert (ensure that the Files plugin is enabled)
2. Search for a file.
3. Press enter.
_Result: nothing happens._

4. Open Albert again.
5. Search for the same file.
6. Press the alternative key modifier.
7. Select "Open with default application".
8. Press enter.
_Result: the registered application opens twice._

#### Source
`albert-git` package in Arch User Repository. The last official Arch package (`albert-0.17.2-1-x86_64.pkg.tar.zst`) does work as expected.

#### Debug output
<details>

```
        Albert version: 0.21.1
            Build date: Jul  6 2023 11:32:59
            Qt version: 6.5.1
             Build ABI: x86_64-little_endian-lp64
  Arch (build/current): x86_64/x86_64
 Kernel (type/version): linux/6.3.9-arch1-1
                    OS: Arch Linux
     OS (type/version): arch/unknown
 $QT_QPA_PLATFORMTHEME: qt5ct
         Platform name: wayland
                  Font: Open Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular
       Binary location: /usr/bin/albert
                  $PWD: /home/b10n/desktop/albert-git
                $SHELL: /bin/zsh
                 $LANG: en_US.UTF-8
              Language: English
                Locale: en_US
     $XDG_SESSION_TYPE: wayland
  $XDG_CURRENT_DESKTOP: sway
      $DESKTOP_SESSION:
  $XDG_SESSION_DESKTOP:
            Icon theme: Papirus-Dark
```
</details>

**Comment by b10n** [comment]
Unfortunately it is still there.

<details>

```
        Albert version: 0.22.0
            Build date: Aug 10 2023 09:10:05
            Qt version: 6.5.2
             Build ABI: x86_64-little_endian-lp64
  Arch (build/current): x86_64/x86_64
 Kernel (type/version): linux/6.4.9-arch1-1
                    OS: Arch Linux
     OS (type/version): arch/unknown
 $QT_QPA_PLATFORMTHEME: qt5ct
         Platform name: wayland
                  Font: Open Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular
       Binary location: /usr/bin/albert
                  $PWD: /home/b10n
                $SHELL: /bin/zsh
                 $LANG: en_US.UTF-8
              Language: English
                Locale: en_US
     $XDG_SESSION_TYPE: wayland
  $XDG_CURRENT_DESKTOP: sway
      $DESKTOP_SESSION:
  $XDG_SESSION_DESKTOP:
            Icon theme: Papirus-Dark
```
</details>

**Comment by ManuelSchneid3r** [comment]
Just saw Platform name: wayland. Did you change the official desktop entry? Because this one does `Exec=/usr/bin/env QT_QPA_PLATFORM=xcb albert`

**Comment by b10n** [comment]
I was not using the desktop entry, so I was running it in native Wayland mode. With that value set, the problem is no longer there! However, it does introduce a graphical glitch: the window is recentered after every resize event (i.e. results update) This makes the window 'jump around' when typing.

**Comment by ManuelSchneid3r** [comment]
Is the bug you mentioned #116 ? Closing this since wayland development is extremely slow and will be a problem for several years for sure. Pure wayland is not supported atm.
