### ISSUE TITLE
Custom python plug-ins not loading

### ISSUE THREAD

**Issue by AdamPS** [albertlauncher/plugins#114]
#### Description
My plug-ins in /home/ZZZ/.local/share/albert/python/plugins are not loading at all. The log shows that albert is searching the correct directory however the plug-ins are ignored.

This was working in 0.22.0, and broke in one of the upgrades since then.

#### Expected behavior
Plug-ins load

#### Steps to reproduce
Create local python plug-ins

#### Source
http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/

#### Debug output

<details>
       Albert version: 0.22.2
            Build date: Aug 14 2023 20:53:25
            Qt version: 6.2.4
             Build ABI: x86_64-little_endian-lp64
  Arch (build/current): x86_64/x86_64
 Kernel (type/version): linux/5.15.0-78-generic
                    OS: Ubuntu 22.04.3 LTS
     OS (type/version): ubuntu/22.04
 $QT_QPA_PLATFORMTHEME: 
         Platform name: xcb
                  Font: Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1
       Binary location: /usr/bin/albert
.....
.....
18:43:59 [debg:python] Searching Python plugins in /home/XXX/.local/share/albert/python/plugins
18:43:59 [debg:python] Searching Python plugins in /usr/share/albert/python/plugins

</details>

**Comment by ManuelSchneid3r** [comment]
Are your plugins single python files or package direcories?

**Comment by AdamPS** [comment]
They are single files. It worked fine in 0.22.0.

**Comment by AdamPS** [comment]
#113 is still not fixed anyway - the first warning still exists because anyway it is a directory. Please can you try and find a different solution?? For example, you could just prevent the warning for the 3 cases mentioned in the issue - for any other file, keep the warning.

**Comment by ManuelSchneid3r** [comment]
this should be fixed in 0.22.3 right?

**Comment by AdamPS** [comment]
Great many thanks

**Comment by ManuelSchneid3r** [comment]
> #113 is still not fixed anyway - the first warning still exists because anyway it is a directory.

> 14:53:45 [warn:python] Python package init file does not exist /home/XXXX/.local/share/albert/python/plugins/pycache

this one?

**Comment by AdamPS** [comment]
With the current code I see 3 warnings again

11:57:49 [warn:python] Python package init file does not exist /home/adam/.local/share/albert/python/plugins/__pycache__
11:57:49 [warn:python] Path is not a python file /usr/share/albert/python/plugins/albert.pyi
11:57:49 [warn:python] Path is not a python file /usr/share/albert/python/plugins/README.md

In 0.22.2 I saw only the first one, however all my plug-ins were broken😃

I guess you could just ignore *.md, *.pyi, __pycache__

**Comment by ManuelSchneid3r** [comment]
https://github.com/albertlauncher/plugins/commit/5eef7b69bb46f8106d977382501e57b18c7c43ec should fix this

**Comment by AdamPS** [comment]
Great thanks
