### ISSUE TITLE
[python] Cannot import `critical()` or similar logging functions

### ISSUE THREAD

**Issue by stevenxxiu** [albertlauncher/plugins#115]
#### Description
The latest release of *Albert Launcher* v0.22.2 breaks importing of `critical()` or similar logging functions directly. The only way is to use `from albert import *`.

Star imports cause linter issues that cannot be fixed. They're frowned upon in *Python*.

#### Expected behavior
The imports work.

#### Steps to reproduce
Errors are:

- `from albert import critical`
    - `[warn:albert] Failed loading plugin 'youtube_steven': ImportError: cannot import name 'critical' from 'albert' (unknown location)`
- `import albert; albert.critical('foo')`
    - `[warn:albert] Failed loading plugin 'youtube_steven': AttributeError: module 'albert' has no attribute 'critical'`

#### Source
Built from source. v0.22.2.

**Comment by ManuelSchneid3r** [comment]
The logging functions are not on module level anymore. They are attached to the module at runtime. Rationale is to get a dedicated logging category. Alternatives would have been per plugin instance, but then you would have to pass your plugin object around just for the logging facilities. Also a sophisitcated logger factory would be an option but that was just to much work for the moment and generally is somehow overkill imho. I am open for a discussion on better approaches, but thats how it is atm.

**Comment by stevenxxiu** [comment]
How is it used then? I see <https://github.com/albertlauncher/python/blob/61a4a678d8f1c32404e6ae0c2d6096ee383a5908/dice_roll/__init__.py#L154> uses `albert.info()`, `albert.warning()`. This errors out.

**Comment by ManuelSchneid3r** [comment]
dice_roll is probably outdated and has to be maintained. just use them directly. they are in the scope of the module. but must not be imported.

**Comment by stevenxxiu** [comment]
So shouldn't `import albert; albert.critical('foo')` work then? It errors out.

**Comment by ManuelSchneid3r** [comment]
You don't have to qualify it. Especially not with albert because the function is not in the albert module. Yes, just call it directly.

**Comment by stevenxxiu** [comment]
Here was my hack to get the linter *Pyflakes* to ignore this. Don't think it's too ideal:

```python
critical = globals().get('critical', lambda _: None)
```

**Comment by ManuelSchneid3r** [comment]
imho readability implies maintainability, which takes precedence over linter output. thats actually the reason why i did not maintain dice_roll, unit_converter and youtube. Its extremely time consuming to read code that could be condensed to like 25%. but i guess thats just a matter of taste. ofc I see that this is still not a proper approach.
