### ISSUE TITLE
Error fetching docset list: Proxy connection refused.

### ISSUE THREAD

**Issue by 10-Kirito** [albertlauncher/plugins#121]
I don’t know why I get the message proxy connection refused every time I turn on my computer recently. It may be a proxy problem, but I haven’t found the relevant option to set up a proxy. Is there any solution?

![Albert_Error](https://github.com/albertlauncher/albert/assets/101441382/0cbfea02-c11f-44c2-86dd-e0cb37c097dd)

**Comment by ManuelSchneid3r** [comment]
are you using it in an office network?

**Comment by 10-Kirito** [comment]
> are you using it in an office network?

No, I just use it for daily use. There was no problem before, but this problem suddenly appeared.

**Comment by ManuelSchneid3r** [comment]
And you have a working internet connection?

**Comment by 10-Kirito** [comment]
> And you have a working regular internet connection?

I can connect to the Internet, everything is normal. But then I thought about it, maybe he wanted to get some request when he started up, but there was some problem with my network at this time (probably a proxy problem). Thank you very much for taking the time to answer, I will turn it off and leave him alone, thank you again.
