### ISSUE TITLE
Docs for plugins are missing?

### ISSUE THREAD

**Issue by Hellzbellz123** [albertlauncher/plugins#123]
i cant seem too find documentation on the website or github for any plugins

am trying too figure out how too ignore subdirectorys of indexed files using the Ignore Patterns tool
```
# expect below regex too index folders in Games but ignore all children of folders in Games. instead it ignores all folders in games
Games/*/*
!Games/*
Source/*/*
Downloads/*/*
!Downloads/*/

```

**Comment by ManuelSchneid3r** [comment]
Was just about to answer this noon but I found a bug and then RL called. Probably you read about ignore files online. This info is outdated. Name filters are global. As stated in the popup. Name filters are regular expressions, not wildcard expressions. And then they are name filters not type filters. Sure maybe you could hack it with some complex regexes but probably it's easier to just exclude it entirely with name filters and then add another index path with directory type filter and a depth of 1.

Documentation moved in app. If you think something is lacking let me know.
