### ISSUE TITLE
[files] About error message when parsing large file index

### ISSUE THREAD

**Issue by zxeoc** [albertlauncher/plugins#59]
**Description**
When albert parses a large file index (~/.cache/albert/org.albert.extension.files/fileindex.json), it gives an error message "ICE default IO error handler doing an exit()" and failed. It's a little hard to find the real reason. Maybe a more exact message would be more helpful. And it would be nice to have a warning message to tell users indexing a large number of files may cause the former issue on the config UI of the "Files" plugin(I saw it in the README of the plugin, but it would be better showing on the UI).

**Expected behavior**
The app gives an error message like "the file index file(~/.cache/albert/org.albert.extension.files/fileindex.json) is too large".

**Steps to reproduce**
- On the config page of "Files", add a path with a large number of files in it to the "Paths" list
- Wait a while when albert indexes the files
- restart albert from terminal

**Additional information (please provide the following information):**
Repo: Arch Linux AUR

<details>
<summary>Output of `albert --report `</summary>
core:         Albert version: 0.17.3
core:             Build date: Jul 26 2022 03:28:46
core:             Qt version: 5.15.5
core:   QT_QPA_PLATFORMTHEME: qt5ct
core:        Binary location: /usr/bin/albert
core:                    PWD: /data/workspace/oldWork
core:                  SHELL: /usr/bin/zsh
core:                   LANG: en_US.UTF-8
core:       XDG_SESSION_TYPE: x11
core:    XDG_CURRENT_DESKTOP: XFCE
core:        DESKTOP_SESSION: xfce
core:    XDG_SESSION_DESKTOP: xfce
core:                     OS: EndeavourOS
core:      OS (type/version): endeavouros/unknown
core:              Build ABI: x86_64-little_endian-lp64
core:   Arch (build/current): x86_64/x86_64
core:  Kernel (type/version): linux/5.18.14-arch1-1
</details>

**Comment by ManuelSchneid3r** [comment]
Is this still an issue in 0.18?
