### ISSUE TITLE
[WBM] Input cursor disappears

### ISSUE THREAD

**Issue by tyilo** [albertlauncher/plugins#67]
#### Source
Arch Linux AUR.

#### Additional info

<details><summary>Albert report output</summary>
core:         Albert version: 0.17.2
core:             Build date: Dec 24 2020 10:03:09
core:             Qt version: 5.15.2
core:   QT_QPA_PLATFORMTHEME: 
core:        Binary location: /usr/bin/albert
core:                    PWD: /home/tyilo
core:                  SHELL: /bin/fish
core:                   LANG: en_US.utf8
core:       XDG_SESSION_TYPE: x11
core:    XDG_CURRENT_DESKTOP: 
core:        DESKTOP_SESSION: awesome
core:    XDG_SESSION_DESKTOP: awesome
core:                     OS: Arch Linux
core:      OS (type/version): arch/unknown
core:              Build ABI: x86_64-little_endian-lp64
core:   Arch (build/current): x86_64/x86_64
core:  Kernel (type/version): linux/5.11.7-arch1-1
</details>

<details><summary>Terminal output</summary>
N/A
</details>

<details><summary>QtDiag output</summary>
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Qt 5.15.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.2.0) on "xcb" 
OS: Arch Linux [linux version 5.11.7-arch1-1]

Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2

Environment:
  QT_SCALE_FACTOR_ROUNDING_POLICY="PassThrough"

Features: QT_NO_EXCEPTIONS

Library info:
  PrefixPath: /usr
  DocumentationPath: /usr/share/doc/qt
  HeadersPath: /usr/include/qt
  LibrariesPath: /usr/lib
  LibraryExecutablesPath: /usr/lib/qt/libexec
  BinariesPath: /usr/bin
  PluginsPath: /usr/lib/qt/plugins
  ImportsPath: /usr/lib/qt/imports
  Qml2ImportsPath: /usr/lib/qt/qml
  ArchDataPath: /usr/lib/qt
  DataPath: /usr/share/qt
  TranslationsPath: /usr/share/qt/translations
  ExamplesPath: /usr/share/doc/qt/examples
  TestsPath: /usr/tests
  SettingsPath: /etc/xdg

Standard paths [*...* denote writable entry]:
  DesktopLocation: "Desktop" */home/tyilo/Desktop*
  DocumentsLocation: "Documents" */home/tyilo/Documents*
  FontsLocation: "Fonts" */home/tyilo/.local/share/fonts* /home/tyilo/.fonts /usr/local/share/fonts /usr/share/fonts
  ApplicationsLocation: "Applications" */home/tyilo/.local/share/applications* /usr/local/share/applications /usr/share/applications
  MusicLocation: "Music" */home/tyilo/Music*
  MoviesLocation: "Movies" */home/tyilo/Videos*
  PicturesLocation: "Pictures" */home/tyilo/Pictures*
  TempLocation: "Temporary Directory" */tmp*
  HomeLocation: "Home" */home/tyilo*
  AppLocalDataLocation: "Application Data" */home/tyilo/.local/share/QtProject/qtdiag* /usr/local/share/QtProject/qtdiag /usr/share/QtProject/qtdiag
  CacheLocation: "Cache" */home/tyilo/.cache/QtProject/qtdiag*
  GenericDataLocation: "Shared Data" */home/tyilo/.local/share* /usr/local/share /usr/share
  RuntimeLocation: "Runtime" */run/user/1000*
  ConfigLocation: "Configuration" */home/tyilo/.config* /etc/xdg
  DownloadLocation: "Download" */home/tyilo/Downloads*
  GenericCacheLocation: "Shared Cache" */home/tyilo/.cache*
  GenericConfigLocation: "Shared Configuration" */home/tyilo/.config* /etc/xdg
  AppDataLocation: "Application Data" */home/tyilo/.local/share/QtProject/qtdiag* /usr/local/share/QtProject/qtdiag /usr/share/QtProject/qtdiag
  AppConfigLocation: "Application Configuration" */home/tyilo/.config/QtProject/qtdiag* /etc/xdg/QtProject/qtdiag

File selectors (increasing order of precedence):
  en_US unix linux arch

Network:
  Using "OpenSSL 1.1.1j  16 Feb 2021", version: 0x101010af

Platform capabilities: ThreadedPixmaps OpenGL ThreadedOpenGL WindowMasks MultipleWindows ForeignWindows NonFullScreenWindows NativeWidgets WindowManagement SyncState RasterGLSurface SwitchableWidgetComposition

Style hints:
  mouseDoubleClickInterval: 400
  mousePressAndHoldInterval: 800
  startDragDistance: 10
  startDragTime: 500
  startDragVelocity: 0
  keyboardInputInterval: 400
  keyboardAutoRepeatRate: 30
  cursorFlashTime: 1200
  showIsFullScreen: 0
  showIsMaximized: 0
  passwordMaskDelay: 0
  passwordMaskCharacter: U+25CF
  fontSmoothingGamma: 1.7
  useRtlExtensions: 0
  setFocusOnTouchRelease: 1
  tabFocusBehavior: Qt::TabFocusAllControls 
  singleClickActivation: 0

Additional style hints (QPlatformIntegration):
  ReplayMousePressOutsidePopup: 0

Theme:
  Platforms requested : unknown,generic
            available : deepin,gtk3,snap,flatpak,xdgdesktopportal
  Styles requested    : Fusion,Windows
         available    : chameleon,Windows,Fusion
  System font         : "Sans Serif" 9

Fonts:
  General font : "Sans Serif" 9
  Fixed font   : "monospace" 9
  Title font   : "Liberation Sans" 12
  Smallest font: "Liberation Sans" 12

Palette:
  QPalette::WindowText: #ff000000
  QPalette::Button: #ffefefef
  QPalette::Light: #ffffffff
  QPalette::Midlight: #ffcacaca
  QPalette::Dark: #ff9f9f9f
  QPalette::Mid: #ffb8b8b8
  QPalette::Text: #ff000000
  QPalette::BrightText: #ffffffff
  QPalette::ButtonText: #ff000000
  QPalette::Base: #ffffffff
  QPalette::Window: #ffefefef
  QPalette::Shadow: #ff767676
  QPalette::Highlight: #ff308cc6
  QPalette::HighlightedText: #ffffffff
  QPalette::Link: #ff0000ff
  QPalette::LinkVisited: #ffff00ff
  QPalette::AlternateBase: #fff7f7f7
  QPalette::NoRole: #ff000000
  QPalette::ToolTipBase: #ffffffdc
  QPalette::ToolTipText: #ff000000
  QPalette::PlaceholderText: #80000000

Screens: 2, High DPI scaling: inactive
# 0 "DP-1-1" Depth: 24 Primary: yes
  Manufacturer: BNQ
  Model: BenQ GW2765-
  Serial number: X6E06962019-
  Geometry: 2560x1440+0+0 Available: 2560x1440+0+0
  Virtual geometry: 5120x1440+0+0 Available: 5120x1440+0+0
  2 virtual siblings
  Physical size: 597x336 mm  Refresh: 59.9506 Hz Power state: 0
  Physical DPI: 108.918,108.857 Logical DPI: 96,96 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 1
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

# 1 "DP-3" Depth: 24 Primary: no
  Manufacturer: Philips Consumer Electronics Company
  Model: PHL 275E1-
  Serial number: 18630
  Geometry: 2560x1440+2560+0 Available: 2560x1440+2560+0
  Virtual geometry: 5120x1440+0+0 Available: 5120x1440+0+0
  2 virtual siblings
  Physical size: 597x336 mm  Refresh: 59.9506 Hz Power state: 0
  Physical DPI: 108.918,108.857 Logical DPI: 96,96 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 1
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

LibGL Vendor: Intel
Renderer: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
Version: 4.6 (Compatibility Profile) Mesa 20.3.4
Shading language: 4.60
Format: Version: 4.6 Profile: 2 Swap behavior: 0 Buffer size (RGB): 8,8,8
Profile: None (QOpenGLFunctions_4_6)

Vulkan instance available
Supported instance extensions:
  VK_KHR_device_group_creation, version 1
  VK_KHR_display, version 23
  VK_KHR_external_fence_capabilities, version 1
  VK_KHR_external_memory_capabilities, version 1
  VK_KHR_external_semaphore_capabilities, version 1
  VK_KHR_get_display_properties2, version 1
  VK_KHR_get_physical_device_properties2, version 2
  VK_KHR_get_surface_capabilities2, version 1
  VK_KHR_surface, version 25
  VK_KHR_surface_protected_capabilities, version 1
  VK_KHR_xcb_surface, version 6
  VK_KHR_xlib_surface, version 6
  VK_EXT_acquire_xlib_display, version 1
  VK_EXT_debug_report, version 9
  VK_EXT_debug_utils, version 2
  VK_EXT_direct_mode_display, version 1
  VK_EXT_display_surface_counter, version 1
  VK_KHR_wayland_surface, version 6
Supported layers:
  VK_LAYER_NV_optimus, version 1, spec version 1.2.155, NVIDIA Optimus layer
  VK_LAYER_VALVE_steam_fossilize_32, version 1, spec version 1.2.136, Steam Pipeline Caching Layer
  VK_LAYER_VALVE_steam_fossilize_64, version 1, spec version 1.2.136, Steam Pipeline Caching Layer
  VK_LAYER_VALVE_steam_overlay_32, version 1, spec version 1.2.136, Steam Overlay Layer
  VK_LAYER_VALVE_steam_overlay_64, version 1, spec version 1.2.136, Steam Overlay Layer
Available physical devices:
  API version 1.2.145, vendor 0x8086, device 0x3E9B, Intel(R) UHD Graphics 630 (CFL GT2), type 1, driver version 20.3.4

Qt Rendering Hardware Interface supported backends:
OpenGL (with default QSurfaceFormat):
  Min Texture Size: 1
  Max Texture Size: 16384
  Max Color Attachments: 8
  Frames in Flight: 1
  Uniform Buffer Alignment: 1
  Supported MSAA sample counts: 1,2,4,8,16
  Features:
    - MultisampleTexture
    v MultisampleRenderBuffer
    - DebugMarkers
    - Timestamps
    v Instancing
    - CustomInstanceStepRate
    v PrimitiveRestart
    v NonDynamicUniformBuffers
    v NonFourAlignedEffectiveIndexBufferOffset
    v NPOTTextureRepeat
    - RedOrAlpha8IsRed
    v ElementIndexUint
    v Compute
    v WideLines
    v VertexShaderPointSize
    v BaseVertex
    - BaseInstance
    v TriangleFanTopology
    v ReadBackNonUniformBuffer
    v ReadBackNonBaseMipLevel
  Texture formats: RGBA8 BGRA8 R8 R16 RED_OR_ALPHA8 RGBA16F RGBA32F R16F R32F D16 D32F BC1 BC2 BC3 ETC2_RGB8 ETC2_RGB8A1 ETC2_RGBA8
Vulkan:
  Min Texture Size: 1
  Max Texture Size: 16384
  Max Color Attachments: 8
  Frames in Flight: 2
  Uniform Buffer Alignment: 64
  Supported MSAA sample counts: 1,2,4,8,16
  Features:
    v MultisampleTexture
    v MultisampleRenderBuffer
    - DebugMarkers
    v Timestamps
    v Instancing
    - CustomInstanceStepRate
    v PrimitiveRestart
    v NonDynamicUniformBuffers
    v NonFourAlignedEffectiveIndexBufferOffset
    v NPOTTextureRepeat
    v RedOrAlpha8IsRed
    v ElementIndexUint
    v Compute
    v WideLines
    v VertexShaderPointSize
    v BaseVertex
    v BaseInstance
    v TriangleFanTopology
    v ReadBackNonUniformBuffer
    v ReadBackNonBaseMipLevel
  Texture formats: RGBA8 BGRA8 R8 R16 RED_OR_ALPHA8 RGBA16F RGBA32F R16F R32F D16 D32F BC1 BC2 BC3 BC4 BC5 BC6H BC7 ETC2_RGB8 ETC2_RGB8A1 ETC2_RGBA8 ASTC_4x4 ASTC_5x4 ASTC_5x5 ASTC_6x5 ASTC_6x6 ASTC_8x5 ASTC_8x6 ASTC_8x8 ASTC_10x5 ASTC_10x6 ASTC_10x8 ASTC_10x10 ASTC_12x10 ASTC_12x12
</details>

#### Steps to reproduce
- Start albert.
- Run `albert toggle`, type something and press escape.
- Run `albert toggle` again and type something. The cursor is gone.

#### Expected behaviour
The cursor should not disappear after the second `albert toggle`.

#### Actual behaviour
The cursor disappears. I haven't found a reliable way of restoring the cursor, without restarting albert.

See video: https://i.imgur.com/cYIv4X6.mp4

**Comment by ManuelSchneid3r** [comment]
I have not experienced this a long time an may qt fixed this
