### ISSUE TITLE
[files] Excluding certain folders

### ISSUE THREAD

**Issue by palmenros** [albertlauncher/plugins#69]
**Why?**

Right now the files extension allows you to add folders to index. However, it's common for modern developing tools to have huge folders such as 'node_modules' or 'venv' or 'vendor' which pollute the search. It would be great if we could add a list of excluded folders (maybe in the form of regex, maybe in the form of exact match) so that the indexer wouldn't go inside them. 

**How?**

I don't exactly know how the indexer is built, but it shouldn't be too hard to check that the current folder name is not a "blacklisted folder name" before recursing into indexing it.

**Comment by ManuelSchneid3r** [comment]
.albertignore files have been dropped entirely in 0.18 use the global exclude mechanism. Let me know if the equivalent problem persists.

**Comment by jerome-rdlv** [comment]
I’m really sorry to learn the removal of the .albertignore files support. I’m using it intensively and it’s the feature that made me chose Albert in the beginning. Could you link me to resources about the *why* of the removal, and maybe to the *how* to replace it with equivalent behavior?

**Comment by ManuelSchneid3r** [comment]
Why: 
because its a niche feature that hardly anybody used, is too complicated to maintain and for regular users to use.
How:
Copy everything to the global exclude file and prepend the path to the subdir the .albertignore file Was located before.

Git/syncthing are sophisticated file managing tool. Of course it makes sense to have such things for these tools. Such mechanisms are overkill for Albert.

**Comment by jerome-rdlv** [comment]
Bad luck for me but thanks for your quick answer.
The global exclude file would be too cumbersome to maintain as I have a lot of filesystem subtrees with their own exclusion logic which it makes sense too keep at each subtree root level.

**Comment by ManuelSchneid3r** [comment]
I don't see the point. If you don't move the subtree often (including the ignore file) that's not a deal breaker.
