### ISSUE TITLE
[frontends] Custom keybindings

### ISSUE THREAD

**Issue by michaelBelsanti** [albertlauncher/plugins#71]
As far as I can tell, there is not currently a way to change the built-in controls, such as the ones for moving up and down in the search. I personally use super+j/k for navigating vertical menus, and I think this would be a beneficial feature to add.

I could've missed something and this is already possible, but I'm not sure.

**Comment by ManuelSchneid3r** [comment]
What exactly do you have in mind? i mean there are arrows and emacs/vim keys. what do you need more than that?

**Comment by michaelBelsanti** [comment]
I am not currently using Albert anymore, I don't recall there being Vim keybinds at the time, but perhaps I just missed them. Either way, it seems this issue is not needed anymore.
