### ISSUE TITLE
No media control plugin available?

### ISSUE THREAD

**Issue by seliver** [albertlauncher/plugins#72]
In previous versions there was a plugin, I'm not sure how it was called, but it existed to control Spotify/Chrome actions like play/pause/next.

In the current version (0.18.3+377), I can't see it in the list:

![image](https://user-images.githubusercontent.com/7545867/210349021-90a8d323-e745-4639-9a28-bc8f66dd9df2.png)

and when I have spotify playing music, the "next" options doesn't appear: 

![image](https://user-images.githubusercontent.com/7545867/210349511-42397770-fb84-455c-9f33-611fe9a9a74c.png)

**Comment by ManuelSchneid3r** [comment]
This plugin is looking for a maintainer. @idkCpp since you authored this plugin it's obvious to ask if you want to actively maintain the plugin. Otherwise we'll have to wait until somebody volunteers @seliver

**Comment by ManuelSchneid3r** [comment]
https://github.com/albertlauncher/plugins/tree/master/.archive/mpris

**Comment by ManuelSchneid3r** [comment]
I dont use it personally therefore there is nobody going to work on it. This plugin needs a maintainer. It seriously needs some overhaul due to the API changes in 0.18. Id appreciate if you'd go ahead and work on it if you need it. Ill close this one since unless somebody volunteers nobody will fix this issue.

**Comment by luksfarris** [comment]
Hi @ManuelSchneid3r, I'm also missing this plugin, and I would like to volunteer to maintain it.
Is there any formal process, or should I just go ahead and work on a PR updating it?

**Comment by ManuelSchneid3r** [comment]
Sure there is https://github.com/albertlauncher/plugins/tree/master/.archive/mpris as a starting point. No formal process, it just has to be reviewed. Move it to the root dir, make it work and send a PR. For questions join telegram/discord chats. Also see https://albertlauncher.github.io/reference/namespacealbert.html.

**Comment by ManuelSchneid3r** [comment]
Drop the icons, the icons for such controls are contained in [QStandardPixmaps](https://doc.qt.io/qt-6/qstyle.html#StandardPixmap-enum). 

![image](https://github.com/albertlauncher/plugins/assets/3252315/9c1a6fa3-14b9-4904-9246-f0ef80c74298)

use them with the (unfortunately undocumented atm) StandardPixmap icon url scheme, like `"qsp:SP_TrashIcon"`

**Comment by ManuelSchneid3r** [comment]
Another implementation hint. Please use the async facilities of dbus. The former version blocked the entire app every now and then when players did not respond immediately
