### ISSUE TITLE
Extensions disappeared?

### ISSUE THREAD

**Issue by alvilag** [albertlauncher/plugins#73]
Hello,

The last update (0.18.6) deleted my preferred settings. It is not a big deal, but I cannot find some of the python extensions that I used before (timer, google translate), and the extension firefox bookmarks. Am I missing something? How can I restore them?

P.S. Thanks for your work! I have been using the launcher for several years now.

**Comment by danielbeaver** [comment]
The Firefox bookmarks extension disappeared from my install as well. If this was removed on purpose, is there a way to add it back in manually?

**Comment by ManuelSchneid3r** [comment]
@danielbeaver It has to be ported and atm nobody wants to maintain it. I personally use chromium. I'd be glad to see some people volunteering here.
 
@alvilag the changes in 0.18 were mostly like a rewrite. The plugin code is still there, but the api has to be adopted. I hope they will find some maintainers and come back over the next weeks/months.
