### ISSUE TITLE
Allow multiple launchers to use the empty trigger

### ISSUE THREAD

**Issue by stevenxxiu** [albertlauncher/plugins#75]
It is convenient to allow multiple launchers to use the empty trigger.

In my case I would want this for browser bookmarks, launching applications, suspending the system.

Currently this creates:

    [warn:albert] Trigger conflict '': Already reserved for applications.

And none of the triggers work.

**Comment by ManuelSchneid3r** [comment]
The empty trigger does not exist, or formally is reserved for the global serach. If your extensions supports the global serch. All the extensions you mentioned are in the global search. you can still trigger the extension to have exlusive results from the triggered extension. No need to give them a common trigger

**Comment by stevenxxiu** [comment]
That's interesting, as I'm not getting this behavior. When I type the trigger for Chromium bookmarks, they show up. But not if I don't type the trigger.

**Comment by ManuelSchneid3r** [comment]
<img width="686" alt="Bildschirm­foto 2023-01-06 um 14 11 30" src="https://user-images.githubusercontent.com/3252315/211018924-b80a0d4e-9a52-46da-97d6-d5753149728e.png">


>[warn:albert] Trigger conflict '': Already reserved for applications. 

how could you achieve this at all? Setting empty triggers is not possible.

**Comment by ManuelSchneid3r** [comment]
Atm the python interface does not support it yet. The code is there so one of the next updates will expose internal classes like globalqueryhandler and index query handler
