### ISSUE TITLE
[chromium] albert's chromium plugin/extension gets shown

### ISSUE THREAD

**Issue by henrikgit** [albertlauncher/plugins#76]
The entry for the chromium plugin (or is it the extension symbol, I don't know) gets shown, although all the possible option entries for Chromium are deactivated in the settings.

![2023-01-07-1302 albert shows its own Chromium entry](https://user-images.githubusercontent.com/6051516/211149779-adf1c255-500d-46a3-a858-386e4e122eb2.png)

**Comment by ManuelSchneid3r** [comment]
This is the plugin item. You can use it to en/disable it. Should not be a problem, currently theres a bug not remembering the usage weighting making this annoying though. I guess I'll fix this today.

**Comment by henrikgit** [comment]
Thank you very much for your quick reply.
It already was disabled:
![2023-01-07-1406 Chromium plugin is already deactivated](https://user-images.githubusercontent.com/6051516/211152250-996f2f76-add2-4dab-b653-800939562c1a.png)


Am I understanding you correctly, that–unrelated to the settings–these entries for plugins still get listed based on their usage weighting?

**Comment by ManuelSchneid3r** [comment]
0.18.8 fixed the weighting issue, which may result in your unused items (plugins) always being displayed before used ones (chromium i guess). Yes plugins are always listed. Its a core extension allowing you to manage your plugins from the launch box.

**Comment by ManuelSchneid3r** [comment]
This is not an issue. As soon as you hit chromium once it should™️ be the first item.
