### ISSUE TITLE
How to refresh items?

### ISSUE THREAD

**Issue by vsuharnikov** [albertlauncher/plugins#77]
I've created a plugin that allows to connect and disconnect known bluetooth devices via `bluetoothctl`. All works as expected, except the only issue: I can't refresh shown items in Albert to replace "Connect XXX" with "Disconnect XXX" after I disconnect XXX. The only way for now is to change the query.

So:
* Can I trigger a refresh?
* Or maybe I can replace an item some way?

If this is not possible, would this functionality be implemented some day?

**Comment by ManuelSchneid3r** [comment]
Why would you want to do that? Dynamic items are a planned feature for real dynamic items like eg. Clock items etc. But I see no real benefit there in your use case.

**Comment by vsuharnikov** [comment]
Sometimes it leads to an unexpected state from the point of user's view, especially with unchecked "Clear input line on hide". For example:
1. I want to connect a bluetooth device.
2. I open Albert and write "bt wi" ("bt " is a trigger).
3. All elements have gone except "Connect WI-1000X".
4. I press Enter, the Albert hides, WI-1000X connects.
5. I want to disconnect WI-1000X.
6. I open Albert, see "bt wi" with one element "Connect WI-1000X". But it is already connected.

Probably, it'd enough to trigger a refresh when the menu opens. So there won't be items, even we have the "bt conn wi-" query in the textbox.

**Comment by ManuelSchneid3r** [comment]
Oh yes thank you for pointing that out. Running the query again is of course necessary

**Comment by ManuelSchneid3r** [comment]
Should be in 18.10
