### ISSUE TITLE
Always center Albert (on primary monitor)

### ISSUE THREAD

**Issue by martinszeltins** [albertlauncher/plugins#78]
Right now the `Always center Albert` option centers Albert on whichever monitor you are currenly active on. I can disable this option but then I have to manually position Albert using `x, y` coordinates which means that if I disconnect from my 2 external monitors and Albert was positioned at `5483, 500` then I won't be able to see Albert at all when I'm on a single screen because the `x` coordinate is offscreen.

**So there are 2 issues currently:**
1. It would be nice to have an option to always center Albert _but only on the primary monitor_.
2. If user chooses to position Albert manually then it should reset `x` position if Albert detects monitor change otherwise a user can end up with Albert offscreen on the 2nd monitor which is not connected anymore.

Let me illustrate the problem with manual positioning and external monitors here:
![image](https://user-images.githubusercontent.com/34019878/210500351-9771a9b2-29d5-4dc6-a343-81dbae67a437.png)

One solution would be to detect that external monitors are disconnected and to reset Albert `x` position.

**Comment by ManuelSchneid3r** [comment]
is this a dupe if #57?

**Comment by ManuelSchneid3r** [comment]
Btw can you please share your theme in the discussions?

**Comment by ManuelSchneid3r** [comment]
@martinszeltins can you please test the feature?
