### ISSUE TITLE
[urlhandler] Does not open url

### ISSUE THREAD

**Issue by bambirombi** [albertlauncher/plugins#80]
In previous versions I was able to open urls from albert directly to the browser. Now, it  searches the url in google instead of opening it.

Albert version: 0.18.10
OS: Manjaro (Gnome)

**Comment by Hajneken** [comment]
I have a similar problem. It seems like the URL is not being recognized in the first place. Is there some trigger symbol to put before the URL that I could not find or the extension is just broken? 

Albert version: 0.18.10
OS: Ubuntu 22.04.1

**Comment by ManuelSchneid3r** [comment]
The functionality went into its own plugin. Obviously it is not a global handler. You should be able to open them triggered (urlhandler). Will fix this asap
