### ISSUE TITLE
[python] No longer able to specify different images for each item

### ISSUE THREAD

**Issue by DenverCoder1** [albertlauncher/plugins#81]
Is it possible to have different icons for each item in 0.18?

It seems as though the first time an icon is used during a session, it keeps using that image even if the query is altered and a different image path is passed.

0.17

<img src="https://user-images.githubusercontent.com/20955511/211493808-37a34fe1-a786-4101-a6cc-bc1e57580f3f.png" width="500px" />

0.18

<img src="https://user-images.githubusercontent.com/20955511/211493881-408127b2-9321-47d2-9135-8a9b5bd8fd30.png" width="500px" />

Even though the `icon` parameter is different when constructing each `Item`, they all show the same icon.

```py
def get_icon_path(num_sides: int | None) -> str:
    icons_path = Path(__file__).parent / "icons"
    # get the icon for the number of sides or d20 if there is no icon for that number
    icon = f"d{num_sides}" if Path(icons_path / f"d{num_sides}.svg").exists() else "d20"
    # use the overall total icon if the number of sides is None
    if num_sides is None:
        icon = "dice"
    # return the path to the icon
    return str(icons_path / f"{icon}.svg")
```
```
albert.Item(
    id=md_name,
    icon=[get_icon_path(num_sides)],
    text=(
        f"Rolled {len(rolls)}d{num_sides} - Total: {sum_rolls}"
        if num_sides
        else f"Overall Total: {sum_rolls}"
    ),
    subtext=f"Rolls: {', '.join(map(str, rolls))}",
    actions=[
        albert.Action(
            id="copytotal",
            text="Copy result to clipboard",
            callable=lambda: albert.setClipboardText(text=str(sum_rolls)),
        ),
        albert.Action(
            id="copyrolls",
            text="Copy result to clipboard",
            callable=lambda: albert.setClipboardText(text=", ".join(map(str, rolls))),
        ),
    ],
)
```

**Comment by ManuelSchneid3r** [comment]
Icons are cached internally using the item id. This is intended to avoid the recurring lookup of the items provided by the Item.icon list. If if you have two different items use different ids. Btw this does also affect sorting of the items.
