### ISSUE TITLE
location for storing snippets

### ISSUE THREAD

**Issue by qsh-zh** [albertlauncher/plugins#86]
I want to move the snippets from my old machine to the new machine. Where can I find the file that stores those snippets?

**Comment by ManuelSchneid3r** [comment]
Does the button in the settings not work?

**Comment by qsh-zh** [comment]
I am not sure there are "import  / export" buttoms in settins.

![image](https://user-images.githubusercontent.com/28699575/212153147-9f0b45be-e5e7-45cf-b333-2d7ab6ed6f65.png)

**Comment by ManuelSchneid3r** [comment]
OH well please update

**Comment by ManuelSchneid3r** [comment]
@qsh-zh this is 0.17. please update
