### ISSUE TITLE
[chromium] bookmarks_path=@invalid()

### ISSUE THREAD

**Issue by hypc** [albertlauncher/plugins#88]
this is a part of my config `~/.config/albert.conf`:

```ini
[chromium]
bookmarks_path=/home/hypc/snap/chromium/common/chromium/Default/Bookmarks
enabled=true
indexHostname=true
```

and if I restart the albert, the config will be change to:

```ini
[chromium]
bookmarks_path=@Invalid()
enabled=true
indexHostname=true
```

OS: Ubuntu22.04
Albert: 0.18.10

**Comment by ManuelSchneid3r** [comment]
[Outch ](https://github.com/albertlauncher/plugins/blob/master/chromium/src/plugin.cpp#L103) ty. fix incoming

**Comment by ManuelSchneid3r** [comment]
One question though: I did not notice this issue because the automated detection worked well for me. Which browser do you use on your system?
