### ISSUE TITLE
Very sluggish with Files plugin

### ISSUE THREAD

**Issue by holmesrichards** [albertlauncher/plugins#90]
#### Description
When the Files plugin is enabled (or being enabled/disabled) Albert is very sluggish, sometimes taking > 20 seconds to respond to user actions. This sluggishness does not occur while Files is disabled. Seems to be associated with file indexing, see debug output.

I am using:

* albert 0.18.13
* System:
  Kernel: 5.15.0-57-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.7
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy

This problem only started occurring recently. Possibly associated with upgrade from Mint 21.0 to 21.1.

#### Expected behavior
Quick response

#### Steps to reproduce
Start Albert. Enable Files if not enabled. 

#### Source
Unknown

#### Debug output

<details>

Response to enabling Files plugin, note 22 second wait.

```
09:10:13 [warn:files] Busy wait for file indexer.
09:10:35 [debg:albert] [24071ms] Successfully unloaded 'files'
```

</details>

**Comment by ManuelSchneid3r** [comment]
faf on my system. can you take a screenie of your files settings and post the entire stdout? system watches enabled?

**Comment by holmesrichards** [comment]
I don't see any settings for Files, where are they?

I don't know anything about system watches.

**Comment by ManuelSchneid3r** [comment]
Settings>extensions>files

**Comment by holmesrichards** [comment]
Adjusted settings and it seems ok now
