### ISSUE TITLE
Calculator plugin does not respect LC_NUMERIC

### ISSUE THREAD

**Issue by mplx** [albertlauncher/plugins#91]
**Description**

The calculator plugin does not respect `LC_NUMERIC` settings; I've set them to `de_DE` (decimal separator `,`) and expect maths like `1,5 + 1,2` to work, however I've still to use `.` als decimal separator (`1.5 + 1.2`).

When running albert with a LANG prefix (see albertlauncher/albert#556; `LANG=de_DE albert` or `LANG=de_DE.utf8 albert`) it still does not do maths when decimale comma is used.

**Expected behavior**

maths with decimal comma work as LC_NUMERIC is set to de_DE which has a decimal comma defined

**Steps to reproduce**

1. set `LC_NUMERIC` to `de_DE.UTF-8`
2. enable calculator plugin in albert
3. maths: `1,4+1,5`

**Additional information (please provide the following information):**

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE=C
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

$ env | grep -E '^LANG|^LC_' | sort
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_COLLATE=C
LC_MEASUREMENT=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
```

<details>
<summary>Output of `albert --report `</summary>

```
Albert version: 0.18.4  
Build date: Jan  4 2023 07:19:31  
Qt version: 6.4.1  
QT_QPA_PLATFORMTHEME:   
Binary location: /usr/bin/albert
PWD: /home/REDACTED
SHELL: /bin/bash
LANG: en_US.UTF-8
XDG_SESSION_TYPE: x11
XDG_CURRENT_DESKTOP: Budgie:GNOME
DESKTOP_SESSION: budgie-desktop
XDG_SESSION_DESKTOP: budgie-desktop
OS: Arch Linux
OS (type/version): arch/unknown
Build ABI: x86_64-little_endian-lp64
Arch (build/current): x86_64/x86_64
Kernel (type/version): linux/6.1.2-arch1-1
```

</details>

<details>
<summary>Output of `albert` when started in a terminal (stdout/stderr)</summary>
12:08:02 [warn:albert] Application has not been terminated graciously

(albert:108053): Gtk-WARNING **: 12:08:02.513: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
12:08:02 [warn:default] Unknown property fill
12:08:02 [warn:default] Unknown property src
12:08:02 [warn:default] Unknown property fill
12:08:02 [warn:default] Unknown property src
12:08:02 [warn:default] Unknown property fill
12:08:02 [warn:default] Unknown property src
</details>

**Comment by ManuelSchneid3r** [comment]
Can you please test 0.19.3?

**Comment by mplx** [comment]
Tested 0.19.3 calculator, works perfectly! Thank you [Manuel](https://github.com/ManuelSchneid3r)! :)

**Comment by ManuelSchneid3r** [comment]
Also check qalculator. It is way better imho.

mplx ***@***.***> schrieb am Mo., 23. Jan. 2023, 09:36:
