### ISSUE TITLE
Help needed - do not index particular file path

### ISSUE THREAD

**Issue by Terminalator** [albertlauncher/plugins#95]
I want Albert to index my home directory **/home/john** except certain directories located there. 

Could someone tell me how I can stop Albert from indexing **/home/john/Steam** ? I'm not good with regular expressions or programming.

Thanks

**Comment by ManuelSchneid3r** [comment]
This is a bug tracker. For support join one of the community chats:

* [Telegram (@albert_launcher_community)](https://telegram.me/albert_launcher_community)
* [Discord](https://discord.gg/enGMWUG)
* [IRC (freenode#albertlauncher)](http://webchat.freenode.net/?channels=%23albertlauncher)

**Comment by ManuelSchneid3r** [comment]
Oh this saved reply is old IRC is on libera

**Comment by ManuelSchneid3r** [comment]
This is a bug tracker. For support join one of the [community chats](https://albertlauncher.github.io/help/#community).
