### ISSUE TITLE
Albert popup is not always centered (v0.20.10)

### ISSUE THREAD

**Issue by uffejakobsen** [albertlauncher/plugins#99]
With the new release v0.20.10 a new bug/problem has appeared - updated from version 0.20.8

The Albert search popup is not always centered - sometimes the popup appears in the top left corner. When closing the popup (with hotkey) and activating is again it is back in center of the screen...

I cannot really figure out what is going on and what triggers this problem

This is a new behavior that was not seen with v0.20.8

**Comment by ManuelSchneid3r** [comment]
0.20.12 has some more debug output. Can you please repeat and post the output?

**Comment by uffejakobsen** [comment]
Output from test - again - the first launch it appears centered - at the second launch it appears in the upper left corner

```
12:30:01 [debg:albert] TIME:      2 µs ['globalsearch':'']
12:30:01 [debg:widgetsboxmodel] DP2-1 Hewlett Packard HP Z24n- 1 QRect(0,0 1920x1200)
12:30:01 [debg:widgetsboxmodel] win_width 712 newX 603 newY 240
12:30:01 [debg:albert] TIME:     30 µs ['datetime':'q']
12:30:01 [debg:albert] TIME:    283 µs ['calculator_qalculate':'q']
12:30:01 [debg:albert] TIME:    565 µs ['albert':'q']
12:30:01 [debg:albert] TIME:   1165 µs ['applications':'q']
12:30:01 [debg:albert] TIME:   1922 µs ['globalsearch':'q']
12:30:01 [info:albert] Detached process started successfully. PID: 71719 QList(sh, -c, qterminal)
12:30:01 [debg:albert] UsageHistory::addActivation   6695 µs
12:30:01 [debg:albert] TIME:      0 µs ['globalsearch':'']
12:30:01 [debg:albert] Query deleted. [#24 'q']
12:30:01 [debg:albert] Query deleted. [#23 '']
12:30:01 [debg:albert] Query deleted. [#19 '']
12:30:01 [debg:albert] UsageHistory::mruScores   5577 µs
12:30:02 [debg:albert] TIME:      0 µs ['globalsearch':'']
12:30:02 [debg:widgetsboxmodel] DP2-1 Hewlett Packard HP Z24n- 1 QRect(0,0 1920x1200)
12:30:02 [debg:widgetsboxmodel] win_width 712 newX 603 newY 240
12:30:02 [debg:albert] TIME:     11 µs ['datetime':'q']
12:30:02 [debg:albert] TIME:     51 µs ['calculator_qalculate':'q']
12:30:02 [debg:albert] TIME:    534 µs ['applications':'q']
12:30:02 [debg:albert] TIME:    164 µs ['albert':'q']
12:30:02 [debg:albert] TIME:   1311 µs ['globalsearch':'q']
12:30:02 [info:albert] Detached process started successfully. PID: 71773 QList(sh, -c, qterminal)
12:30:02 [debg:albert] UsageHistory::addActivation  10318 µs
12:30:02 [debg:albert] TIME:      1 µs ['globalsearch':'']
12:30:02 [debg:albert] Query deleted. [#27 'q']
12:30:02 [debg:albert] Query deleted. [#26 '']
12:30:02 [debg:albert] Query deleted. [#22 '']
12:30:02 [debg:albert] UsageHistory::mruScores   3410 µs
```

**Comment by ManuelSchneid3r** [comment]
> 12:30:01 [debg:widgetsboxmodel] win_width 712 newX 603 newY 240
> 12:30:02 [debg:widgetsboxmodel] win_width 712 newX 603 newY 240

these look perfectly fine. next step is to print x and y in the move event received.

**Comment by ManuelSchneid3r** [comment]
0.20.13 has some more debug output. Can you please repeat and post the output? :D

**Comment by ManuelSchneid3r** [comment]
> 16:29:12 [debg:widgetsboxmodel] win_width 712 newX 603 newY 240
> 16:29:14 [debg:widgetsboxmodel] win_width 712 newX 603 newY 240
> 16:29:14 [debg:widgetsboxmodel] moveEvent QPoint(603,240) > QPoint(0,0)

Okay looks like either a Qt or lxqt compositor bug. Since I have not seen this in cinnamon, gnome and kde yet I assume this is an lxqt bug.

**Comment by ManuelSchneid3r** [comment]
I just installed lxqt on my linux mint test System. I dint know that the window manager has to be chosen. Which wm have you configured on your system and does changing it solve the problem?

**Comment by uffejakobsen** [comment]
> I just installed lxqt on my linux mint test System. I dint know that the window manager has to be chosen. Which wm have you configured on your system and does changing it solve the problem?
I'm running `openbox` - I'm not near my test-system before next week

**Comment by palinek** [comment]
FYI... this issue seems similar to something seen in lxqt-runner -> https://github.com/lxqt/lxqt-runner/commit/703db225dfa722af66e330547a3353238e76ec38

**Comment by ManuelSchneid3r** [comment]
@uffejakobsen is it a problem in your openbox instance only? Does using mutter etc also show this problem? As stated by lxQt guys this is none of their business. since it works on linux mint i assume it is a regression in openbox for now.

**Comment by ManuelSchneid3r** [comment]
@uffejakobsen please contact [openbox](http://openbox.org/wiki/Openbox:Contribute#Bug_reports). I dont think it makes sense to fix their issue in each and every app.
